FROM python3
RUN apt install -y git
RUN git clone https://github.com/momosecurity/Mloger.git
RUN cd Mloger/server && pip3 install -r requirements.txt
EXPOSE 8000
CMD ["python3", "Mloger/server/app.py"]


